EmployeeRepositoryExample/Areas/Admin/Controllers/DetailsController.cs
using EmployeeRepositoryExample.Models;
using EmployeeRepositoryExample.Models.ViewModels;
using EmployeeRepositoryExample.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmployeeRepositoryExample.Areas.Admin.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public DetailsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Details> detailsList = _unitOfWork.Details.GetAll();
            return View(detailsList);
        }

       //Get for Edit
        public IActionResult Upsert(int? id)
        {
            DetailsVM detailsVM = new()
            {
                details = new(),
                EmployeeList = _unitOfWork.Employee.GetAll().Select(e => new SelectListItem
                {
                    Text = e.Name,
                    Value = e.Id.ToString()
                }),
                PositionList = _unitOfWork.Position.GetAll().Select(e=>new SelectListItem
                {
                    Text = e.Designation,
                    Value = e.Id.ToString()
                })
            };

			if (id == 0 || id == null)
            {
                //ViewBag.EmployeeList = EmployeeList; 
                //ViewBag.PositionList = PositionList;
				// create details
				return View(detailsVM);
            }
            else
            {
                // update details
            }
            return View(detailsVM);
        }

        [HttpPost,ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        //POSt for Edit
        public IActionResult Upsert(Details deta)
        {
            if (ModelState.IsValid)
            {
                //var employeeEdit = _db.Employees.Where(x=>x.)
                _unitOfWork.Details.Add(deta);
                _unitOfWork.Save();
				return RedirectToAction("Index");
			}
            return View(deta);
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var employeeGet = _unitOfWork.Details.GetFirstOrDefault(x => x.Id == id);
            if (employeeGet == null)
            {
                return NotFound();
            }
            return View(employeeGet);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(int? id)
        {
            var obj = _unitOfWork.Details.GetFirstOrDefault(x => x.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Details.Remove(obj);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

EmployeeRepositoryExample/Areas/Admin/Controllers/PositionController.cs
using EmployeeRepositoryExample.Models;
using EmployeeRepositoryExample.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeRepositoryExample.Areas.Admin.Controllers
{
    public class PositionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PositionController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Position> positionList = _unitOfWork.Position.GetAll();
            return View(positionList);
        }

        // Get Action method
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Position pos)
        {
            _unitOfWork.Position.Add(pos);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        //Get for Edit
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var employeeGet = _unitOfWork.Position.GetFirstOrDefault(x => x.Id == id);
            if (employeeGet == null)
            {
                return NotFound();
            }
            return View(employeeGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POSt for Edit
        public IActionResult Edit(Position pos)
        {
            //var employeeEdit = _db.Employees.Where(x=>x.)
            _unitOfWork.Position.Update(pos);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var employeeGet = _unitOfWork.Position.GetFirstOrDefault(x => x.Id == id);
            if (employeeGet == null)
            {
                return NotFound();
            }
            return View(employeeGet);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(int? id)
        {
            var obj = _unitOfWork.Position.GetFirstOrDefault(x => x.Id == id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Position.Remove(obj);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

EmployeeRepositoryExample/Controllers/EmployeeController.cs
using EmployeeRepositoryExample.Models;
using EmployeeRepositoryExample.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeRepositoryExample.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<Employee> employeeList = _unitOfWork.Employees.GetAll();
            return View(employeeList);
        }

        // Get Action method
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee emp)
        {
            _unitOfWork.Employees.Add(emp);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        //Get for Edit
        public IActionResult Edit(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var employeeGet = _unitOfWork.Employees.GetFirstOrDefault(x=>x.Id==id);
            if(employeeGet == null)
            {
                return NotFound();
            }
            return View(employeeGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POSt for Edit
        public IActionResult Edit(Employee emp)
        {
            //var employeeEdit = _db.Employees.Where(x=>x.)
            _unitOfWork.Employees.Update(emp);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            var employeeGet = _unitOfWork.Employees.GetFirstOrDefault(x => x.Id == id);
            if (employeeGet == null)
            {
                return NotFound();
            }
            return View(employeeGet);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirm(int? id)
        {
            var obj = _unitOfWork.Employees.GetFirstOrDefault(x=>x.Id==id);
            if (obj == null)
            {
                return NotFound();
            }
            _unitOfWork.Employees.Remove(obj);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

EmployeeRepositoryExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeRepositoryExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeRepositoryExample.styles.css" asp-append-version="true" />
</head>
<body style="background-image:linear-gradient(#fed0c5,#8b47c5)">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" style="background-image:linear-gradient(#fd9869,#fec9c9)">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Repository Example</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" href="#" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Employees Credentials 
                            </a>
                            <div class="dropdown-menu" style="background-image:linear-gradient(#0c7bb3,#f2bae8)">
                                <a class="dropdown-item text-dark"  asp-area="Admin" asp-controller="Employee" asp-action="Index">Details</a>
                                <a class="dropdown-item text-dark"  asp-area="Admin" asp-controller="Position" asp-action="Index">Designation</a>
                                <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="Details" asp-action="Index">Company</a>

                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   @* <footer class="border-top footer fixed-bottom text-muted">
        <div class="container">
            &copy; 2023 - EmployeeRepositoryExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>